FROM node:22.18.0-alpine3.22

# Install build tools and required dependencies
RUN apk add --no-cache \
    python3 \
    build-base \
    pkgconf \
    libunwind-dev

# Set working directory
WORKDIR /app

# Copy source code
COPY . .

# Install dependencies
RUN npm ci

# Default command runs tests
CMD ["npm", "run", "test-ci"]