name: NodeCI

on:
  push:

env:
  NAPI_VERSION: 9
  BINDING_NAME: vlad_fresha_segfault_handler

jobs:
  build-and-test:
    name: Build ${{ format('node:{0}-alpine3.22', matrix.node-version) }} on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    container: ${{ format('node:{0}-alpine3.22', matrix.node-version) }}
    
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, ubuntu-24.04-arm]
        node-version: [20, 22, 24]

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "${{ matrix.node-version }}.x"

      - name: Run Alpine build & test in container on the native runner
        shell: bash
        run: |
          docker run --rm -v ${{ github.workspace }}:/work \
            -e CI=1 -e npm_config_build_from_source=1 -e NAPI_VERSION -e BINDING_NAME \
            node:${{ matrix.node-version }}-alpine3.22 \
            sh -c "
              export ARCH=${{ matrix.os == 'ubuntu-24.04-arm' && 'arm64' || 'amd64' }}
              apk update
              apk add build-base git python3 bash musl-dev linux-headers libunwind-dev libunwind-static
              cd /work
              npm install
              npm run rebuild -- --arch=${ARCH}
              mkdir -p prebuilds/$BINDING_NAME-linux-${ARCH}
              cp build/Release/$BINDING_NAME.node prebuilds/$BINDING_NAME-linux-${ARCH}/node-napi-v$NAPI_VERSION.node
              npm run test-ci
            "

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.os }}-node${{ matrix.node-version }}-prebuilds
          path: prebuilds
          retention-days: 1

  bundle:
    name: Bundle prebuilds
    needs: build-and-test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v4
        with:
          path: tmp

      - name: Display structure of downloaded files
        run: |
          mkdir prebuilds
          cp -R tmp/*/* prebuilds/

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: all-prebuilds
          path: prebuilds
          retention-days: 7
