name: NodeCI

on:
  push:

env:
  NAPI_VERSION: 9
  BINDING_NAME: vlad_fresha_segfault_handler

jobs:
  test:
    name: Test ${{ matrix.image }} (${{ matrix.stack-lib }}) on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, ubuntu-24.04-arm]
        image: [node:20-alpine3.22, node:22-alpine3.22, node:24-alpine3.22, node:20, node:22, node:24]
        stack-lib: [glibc, libunwind]
        exclude:
          # Alpine containers don't use glibc
          - image: node:20-alpine3.22
            stack-lib: glibc
          - image: node:22-alpine3.22
            stack-lib: glibc
          - image: node:24-alpine3.22
            stack-lib: glibc

    steps:
      - uses: actions/checkout@v4

      - name: Build & test in native container
        shell: bash
        run: |
          docker run --rm -v ${{ github.workspace }}:/work \
            -e CI=1 -e npm_config_build_from_source=1 -e NAPI_VERSION -e BINDING_NAME -e STACK_LIB=${{ matrix.stack-lib }} \
            ${{ matrix.image }} \
            sh -c "
              export ARCH=${{ matrix.os == 'ubuntu-24.04-arm' && 'arm64' || 'amd64' }}

              # Install dependencies based on container type and stack library
              if command -v apk > /dev/null; then
                # Alpine Linux (always uses libunwind)
                apk update
                apk add build-base git python3 musl-dev linux-headers libunwind-dev libunwind-static
              else
                # Debian-based - always install basic deps plus specific stack unwinding library
                apt-get update
                apt-get install -y build-essential git python3 pkg-config
                if [ '${{ matrix.stack-lib }}' = 'libunwind' ]; then
                  apt-get install -y libunwind-dev
                else
                  # For glibc builds, ensure execinfo is available (usually built-in)
                  apt-get install -y libc6-dev
                fi
              fi

              cd /work
              npm install
              npm run rebuild -- --arch=\${ARCH}
              mkdir -p prebuilds/$BINDING_NAME-linux-\${ARCH}
              cp build/Release/$BINDING_NAME.node prebuilds/$BINDING_NAME-linux-\${ARCH}/node-napi-v$NAPI_VERSION.node
              npm run test-ci
            "
